### ISSUE TITLE
Ayuda para consumir la API y autenticación - SiiApi

### ISSUE THREAD

**Issue by brianmestre** [aaguirreu/SiiApi#1]
Hola,

Estoy intentando consumir la API de este repositorio para enviar DTEs y boletas, pero me he encontrado con un error relacionado con la autenticación. Al hacer una solicitud a la ruta:

api/v1/pasarela/certificacion/dte/envio

Recibo el siguiente error:

`{
    "message": "Unauthenticated."
}`

He estado enviando el token en la cabecera, pero parece que algo está faltando o no lo estoy enviando de la manera correcta. ¿Podrías orientarme sobre la forma adecuada de manejar la autenticación en esta API? ¿Debo seguir algún formato específico para el envío del token?

Además, tengo algunas otras dudas:

¿Es necesario contar con algún tipo de certificación o clave especial para poder usar la API en el ambiente de certificación/producción?
¿Existe alguna documentación más detallada sobre el consumo de la API, configuraciones, y flujo general de uso?
Cualquier información que puedas proporcionar me será de gran ayuda para poder integrar esta API correctamente en mi proyecto.

Muchas gracias por tu tiempo y apoyo.

Saludos,
brianmestre

**Comment by aaguirreu** [comment]
Hola! te recomiendo utilizar directamente la librería de LibreDTE que actualizaron hace poco: https://github.com/LibreDTE/libredte-lib-core

Éxito en tu proyecto!
